#!/usr/bin/env bash
# Write a bash command that pings IP address as an arguement

count=5
input_address="$1"

if [ $input_address ]; then
  for ((i=0; i<$count; i++))
  do
    ping -c 1 $input_address
  done
else
  echo "Usage: $0 <IP_ADDRESS>"
fi

