#!/usr/bin/env bash
# Write a bash command that pings IP address as an arguement

count=5
input_address="$1"

if [ $input_address ]; then
  ping -c 5 $input_address
else
  echo "Usage: $0 <IP_ADDRESS>"
fi

