#!/usr/bin/env bash
# answer to configuration of firewall on ubuntu
sudo apt-get -y update
sudo apt-get -y install ufw

sudo ufw disable
sudo ufw allow 22/tcp
sudo ufq allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw status

sudo ufw enable
